from django.conf import settings


AUDIT_LOG_SHORT_COMMENT_LENGTH = getattr(settings, 'AUDIT_LOG_SHORT_COMMENT_LENGTH', 130)
RAISE_EXCEPTION_ON_MULTIPLE_MODEL_REGISTRATION = getattr(
    settings, 'RAISE_EXCEPTION_ON_MULTIPLE_MODEL_REGISTRATION', True
)
