# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-08 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reversion', '0005_auto_20160518_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='fingerprint',
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
    ]
